name: flutter_keycloak
description: A Flutter Keycloak wrapper, to manage the authentication and tokens automatically
version: 1.1.4
homepage: https://github.com/TheFe91/flutter_keycloak

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.2
  flutter_secure_storage: ^8.0.0
  get_storage: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.1

flutter: